# Site settings
title: Mitchell J. Feldmann
description: |

    <b> Postdoctoral Researcher </b> helping to improve <b> Strawberry </b> at the <b>University of California, Davis Strawberry Breeding Program</b>.
    
    <b>Ph.D.</b> @ University of California, Davis studying <b>quantitative genetics & cultivated strawberry</b>. 
  
    Deeply interested in <b>mathematics & biology</b>.
    
    Thoughts and opinions are my own and do not reflect the views of my employer.
    
    Warm Regards.
  
owner: Mitchell J. Feldmann
first_published: 2020
email: mjfeldmann@ucdavis.edu
baseurl: "" 
url: "mjfeldmann.github.io" # the base hostname & protocol for your site

title_image: "https://mjfeldmann.github.io/icons/mitch.JPG"
twitter_username: MitchFeldmann

social:
  twitter: https://twitter.com/MitchFeldmann
  github: https://github.com/mjfeldmann
  linkedin-square: https://www.linkedin.com/in/mjfeldmann/
  google: https://scholar.google.com/citations?user=NMlhaEsAAAAJ&hl=en
  email: "mailto:mjfeldmann@ucdavis.edu"

# Build settings
markdown: kramdown

#sass:
#  style: compressed

gems:
  - jekyll-sitemap